# Generated by Django 4.1.13 on 2023-11-06 02:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(max_length=20, unique=True, validators=[core.models.validate_not_empty]),
        ),
    ]
