# Generated by Django 3.2.22 on 2023-10-22 05:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 5, 11, 23, 790145, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
